project:
  type: website

execute:
  freeze: auto

website:
  title: "Gestion de la confidentialité"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



