name: Deploy Quarto Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: inseefrlab/onyxia-rstudio:latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("quarto", "dplyr", "ggplot2"))'

    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
